name: Check

on: push
jobs:
  lint:
    runs-on: win-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint 
